resources:
- ../../base
patchesStrategicMerge:
- memorylimit_patch.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: daily-
images:
- name: sawyerwu/simpledemo
  newName: sawyerwu/simpledemo
  newTag: v8
