apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpledemo
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: simpledemo
        resources:
          limits:
            cpu: "0.5"
            memory: 0.5Gi
          requests:
            cpu: "0.3"
            memory: 0.3Gi
